// <auto-generated />
using System;
using AuroraDbManager.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuroraDbManager.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001085631_AddInstances")]
    partial class AddInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Instances.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cpu")
                        .HasColumnType("integer")
                        .HasColumnName("cpu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("engine");

                    b.Property<int>("MemoryMb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_mb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("StorageGb")
                        .HasColumnType("integer")
                        .HasColumnName("storage_gb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_instances");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_instances_created_at");

                    b.ToTable("instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_instances_cpu", "cpu > 0");

                            t.HasCheckConstraint("ck_instances_engine", "engine IN ('postgres', 'mysql')");

                            t.HasCheckConstraint("ck_instances_memory_mb", "memory_mb > 0");

                            t.HasCheckConstraint("ck_instances_status", "status IN ('provisioning', 'running', 'stopped', 'failed')");

                            t.HasCheckConstraint("ck_instances_storage_gb", "storage_gb > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
