// <auto-generated />
using System;
using AuroraDbManager.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuroraDbManager.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003085158_AddRestoreDatabaseJobs")]
    partial class AddRestoreDatabaseJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Backups.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("storage_type");

                    b.HasKey("Id")
                        .HasName("pk_backups");

                    b.HasIndex("DatabaseId", "CreatedAt")
                        .HasDatabaseName("ix_backups_database_id_created_at");

                    b.ToTable("backups", null, t =>
                        {
                            t.HasCheckConstraint("ck_backups_artifact", "(status = 'completed') = (path IS NOT NULL AND size_bytes IS NOT NULL)");

                            t.HasCheckConstraint("ck_backups_size_bytes", "size_bytes IS NULL OR size_bytes > 0");

                            t.HasCheckConstraint("ck_backups_status", "status IN ('pending', 'running', 'completed', 'failed')");

                            t.HasCheckConstraint("ck_backups_storage_type", "storage_type IN ('local', 's3')");
                        });
                });

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Databases.Database", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_databases");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_databases_instance_id");

                    b.HasIndex("InstanceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_databases_instance_id_name");

                    b.ToTable("databases", null, t =>
                        {
                            t.HasCheckConstraint("ck_databases_status", "status IN ('creating', 'ready', 'deleting', 'failed')");
                        });
                });

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Instances.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cpu")
                        .HasColumnType("integer")
                        .HasColumnName("cpu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("engine");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<int>("MemoryMb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_mb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("StorageGb")
                        .HasColumnType("integer")
                        .HasColumnName("storage_gb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_instances");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_instances_created_at");

                    b.ToTable("instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_instances_cpu", "cpu > 0");

                            t.HasCheckConstraint("ck_instances_engine", "engine IN ('postgres', 'mysql')");

                            t.HasCheckConstraint("ck_instances_memory_mb", "memory_mb > 0");

                            t.HasCheckConstraint("ck_instances_status", "status IN ('provisioning', 'running', 'stopped', 'failed')");

                            t.HasCheckConstraint("ck_instances_storage_gb", "storage_gb > 0");
                        });
                });

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("BackupId")
                        .HasColumnType("uuid")
                        .HasColumnName("backup_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("DatabaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_database_id_unfinished")
                        .HasFilter("status IN ('pending', 'running') AND database_id IS NOT NULL");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_jobs_instance_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_jobs_status");

                    b.HasIndex("InstanceId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_instance_id_type_unfinished")
                        .HasFilter("status IN ('pending', 'running') AND database_id IS NULL");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_attempt", "attempt >= 0 AND attempt <= max_attempts");

                            t.HasCheckConstraint("ck_jobs_backup_id", "(type IN ('backup_database', 'restore_database') AND backup_id IS NOT NULL) OR (type NOT IN ('backup_database', 'restore_database') AND backup_id IS NULL)");

                            t.HasCheckConstraint("ck_jobs_database_id", "(type IN ('create_database', 'delete_database', 'backup_database', 'restore_database') AND database_id IS NOT NULL) OR (type NOT IN ('create_database', 'delete_database', 'backup_database', 'restore_database') AND database_id IS NULL)");

                            t.HasCheckConstraint("ck_jobs_max_attempts", "max_attempts > 0");

                            t.HasCheckConstraint("ck_jobs_status", "status IN ('pending', 'running', 'completed', 'failed')");

                            t.HasCheckConstraint("ck_jobs_type", "type IN ('provision_instance', 'create_database', 'delete_database', 'backup_database', 'restore_database')");
                        });
                });

            modelBuilder.Entity("AuroraDbManager.Api.Infrastructure.Secrets.InstanceSecret", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProtectedAdminPassword")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("protected_admin_password");

                    b.HasKey("InstanceId")
                        .HasName("pk_instance_secrets");

                    b.ToTable("instance_secrets", (string)null);
                });

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Backups.Backup", b =>
                {
                    b.HasOne("AuroraDbManager.Api.Domain.Databases.Database", null)
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backups_databases_database_id");
                });

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Databases.Database", b =>
                {
                    b.HasOne("AuroraDbManager.Api.Domain.Instances.Instance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_databases_instances_instance_id");
                });

            modelBuilder.Entity("AuroraDbManager.Api.Domain.Jobs.Job", b =>
                {
                    b.HasOne("AuroraDbManager.Api.Domain.Instances.Instance", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_instances_instance_id");
                });

            modelBuilder.Entity("AuroraDbManager.Api.Infrastructure.Secrets.InstanceSecret", b =>
                {
                    b.HasOne("AuroraDbManager.Api.Domain.Instances.Instance", null)
                        .WithOne()
                        .HasForeignKey("AuroraDbManager.Api.Infrastructure.Secrets.InstanceSecret", "InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instance_secrets_instances_instance_id");
                });
#pragma warning restore 612, 618
        }
    }
}
